
var createFFmpegCore = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(createFFmpegCore) {
  createFFmpegCore = createFFmpegCore || {};


var e;e||(e=typeof createFFmpegCore !== 'undefined' ? createFFmpegCore : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});e.quit=function(a){if(e.onExit)e.onExit(a);throw new ca(a);};e.exit=da;ea=k=function(){};var fa={},l;for(l in e)e.hasOwnProperty(l)&&(fa[l]=e[l]);var ha=[],ia="./this.program";function ja(a,b){throw b;}var ka=!1,m=!1,la=!1,ma=!1;ka="object"===typeof window;m="function"===typeof importScripts;la="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;
ma=!ka&&!la&&!m;var v="",na,oa,pa,qa;
if(la)v=m?require("path").dirname(v)+"/":__dirname+"/",na=function(a,b){pa||(pa=require("fs"));qa||(qa=require("path"));a=qa.normalize(a);return pa.readFileSync(a,b?null:"utf8")},oa=function(a){a=na(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ia=process.argv[1].replace(/\\/g,"/")),ha=process.argv.slice(2),process.on("uncaughtException",function(a){if(!(a instanceof ca))throw a;}),process.on("unhandledRejection",w),ja=function(a){process.exit(a)},e.inspect=
function(){return"[Emscripten Module object]"};else if(ma)"undefined"!=typeof read&&(na=function(a){return read(a)}),oa=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ha=scriptArgs:"undefined"!=typeof arguments&&(ha=arguments),"function"===typeof quit&&(ja=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=
console.error="undefined"!==typeof printErr?printErr:print);else if(ka||m)m?v=self.location.href:"undefined"!==typeof document&&document.currentScript&&(v=document.currentScript.src),_scriptDir&&(v=_scriptDir),0!==v.indexOf("blob:")?v=v.substr(0,v.lastIndexOf("/")+1):v="",na=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},m&&(oa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var ea=e.print||console.log.bind(console),k=e.printErr||console.warn.bind(console);for(l in fa)fa.hasOwnProperty(l)&&(e[l]=fa[l]);fa=null;e.arguments&&(ha=e.arguments);e.thisProgram&&(ia=e.thisProgram);e.quit&&(ja=e.quit);var ra=0,sa;e.wasmBinary&&(sa=e.wasmBinary);var noExitRuntime;e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);"object"!==typeof WebAssembly&&w("no native wasm support detected");var ta,ua=!1;function assert(a,b){a||w("Assertion failed: "+b)}
function va(a){var b=e["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function wa(a,b,c,d){var f={string:function(q){var t=0;if(null!==q&&void 0!==q&&0!==q){var x=(q.length<<2)+1;t=xa(x);y(q,t,x)}return t},array:function(q){var t=xa(q.length);A.set(q,t);return t}},g=va(a),h=[];a=0;if(d)for(var p=0;p<d.length;p++){var r=f[c[p]];r?(0===a&&(a=B()),h[p]=r(d[p])):h[p]=d[p]}c=g.apply(null,h);c=function(q){return"string"===b?D(q):"boolean"===b?!!q:q}(c);0!==a&&F(a);return c}var ya="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function za(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ya)return ya.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function D(a,b){return a?za(G,a,b):""}
function Aa(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var p=a.charCodeAt(++g);h=65536+((h&1023)<<10)|p&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}function y(a,b,c){return Aa(a,G,b,c)}
function Ba(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ca(a){var b=Ba(a)+1,c=Da(b);c&&Aa(a,A,c,b);return c}function Ea(a){var b=Ba(a)+1,c=xa(b);Aa(a,A,c,b);return c}function Fa(a,b,c){for(var d=0;d<a.length;++d)A[b++>>0]=a.charCodeAt(d);c||(A[b>>0]=0)}var Ga,A,G,Ha,Ia,H,Ja,I,Ka;
function La(a){Ga=a;e.HEAP8=A=new Int8Array(a);e.HEAP16=Ha=new Int16Array(a);e.HEAP32=H=new Int32Array(a);e.HEAPU8=G=new Uint8Array(a);e.HEAPU16=Ia=new Uint16Array(a);e.HEAPU32=Ja=new Uint32Array(a);e.HEAPF32=I=new Float32Array(a);e.HEAPF64=Ka=new Float64Array(a)}var Ma=e.INITIAL_MEMORY||33554432;e.wasmMemory?ta=e.wasmMemory:ta=new WebAssembly.Memory({initial:Ma/65536,maximum:16384});ta&&(Ga=ta.buffer);Ma=Ga.byteLength;La(Ga);var J,Na=[],Oa=[],Pa=[],Qa=[],Ra=[];
function Sa(){var a=e.preRun.shift();Na.unshift(a)}var Ta=0,Ua=null,Va=null;function Wa(){Ta++;e.monitorRunDependencies&&e.monitorRunDependencies(Ta)}function Xa(){Ta--;e.monitorRunDependencies&&e.monitorRunDependencies(Ta);if(0==Ta&&(null!==Ua&&(clearInterval(Ua),Ua=null),Va)){var a=Va;Va=null;a()}}e.preloadedImages={};e.preloadedAudios={};function w(a){if(e.onAbort)e.onAbort(a);k(a);ua=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}
function Ya(a){var b=Za;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function $a(){return Ya("data:application/octet-stream;base64,")}var Za="ffmpeg-core.wasm";if(!$a()){var ab=Za;Za=e.locateFile?e.locateFile(ab,v):v+ab}function bb(){try{if(sa)return new Uint8Array(sa);if(oa)return oa(Za);throw"both async and sync fetching of the wasm failed";}catch(a){w(a)}}
function eb(){return sa||!ka&&!m||"function"!==typeof fetch||Ya("file://")?Promise.resolve().then(bb):fetch(Za,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Za+"'";return a.arrayBuffer()}).catch(function(){return bb()})}var L,N;function fb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.vf;"number"===typeof c?void 0===b.ne?J.get(c)():J.get(c)(b.ne):c(void 0===b.ne?null:b.ne)}}}
function gb(a){return a.replace(/\b_Z[\w\d_]+/g,function(b){return b===b?b:b+" ["+b+"]"})}function hb(a,b){a=new Date(1E3*H[a>>2]);H[b>>2]=a.getUTCSeconds();H[b+4>>2]=a.getUTCMinutes();H[b+8>>2]=a.getUTCHours();H[b+12>>2]=a.getUTCDate();H[b+16>>2]=a.getUTCMonth();H[b+20>>2]=a.getUTCFullYear()-1900;H[b+24>>2]=a.getUTCDay();H[b+36>>2]=0;H[b+32>>2]=0;H[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;hb.Ge||(hb.Ge=Ca("GMT"));H[b+40>>2]=hb.Ge;return b}
function ib(){function a(h){return(h=h.toTimeString().match(/\(([A-Za-z ]+)\)$/))?h[1]:"GMT"}if(!jb){jb=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var f=d.getTimezoneOffset(),g=Math.max(b,f);H[kb()>>2]=60*g;H[lb()>>2]=Number(b!=f);c=a(c);d=a(d);c=Ca(c);d=Ca(d);f<b?(H[mb()>>2]=c,H[mb()+4>>2]=d):(H[mb()>>2]=d,H[mb()+4>>2]=c)}}var jb;
function nb(a,b){ib();a=new Date(1E3*H[a>>2]);H[b>>2]=a.getSeconds();H[b+4>>2]=a.getMinutes();H[b+8>>2]=a.getHours();H[b+12>>2]=a.getDate();H[b+16>>2]=a.getMonth();H[b+20>>2]=a.getFullYear()-1900;H[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);H[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;H[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;H[b+32>>2]=a;a=H[mb()+(a?4:0)>>2];
H[b+40>>2]=a;return b}function pb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function qb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=pb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function rb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function sb(a){if("/"===a)return"/";a=qb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function tb(a,b){return qb(a+"/"+b)}function ub(a){return H[vb()>>2]=a}
function xb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(la)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){w("randomDevice")}}
function yb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:O.cwd();if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=pb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}
function zb(a,b){function c(h){for(var p=0;p<h.length&&""===h[p];p++);for(var r=h.length-1;0<=r&&""===h[r];r--);return p>r?[]:h.slice(p,r-p+1)}a=yb(a).substr(1);b=yb(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,g=0;g<d;g++)if(a[g]!==b[g]){f=g;break}d=[];for(g=f;g<a.length;g++)d.push("..");d=d.concat(b.slice(f));return d.join("/")}var Ab=[];function Bb(a,b){Ab[a]={input:[],output:[],Rd:b};O.De(a,Cb)}
var Cb={open:function(a){var b=Ab[a.node.rdev];if(!b)throw new O.nd(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Rd.flush(a.tty)},flush:function(a){a.tty.Rd.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Rd.Re)throw new O.nd(60);for(var f=0,g=0;g<d;g++){try{var h=a.tty.Rd.Re(a.tty)}catch(p){throw new O.nd(29);}if(void 0===h&&0===f)throw new O.nd(6);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.Rd.Ae)throw new O.nd(60);
try{for(var f=0;f<d;f++)a.tty.Rd.Ae(a.tty,b[c+f])}catch(g){throw new O.nd(29);}d&&(a.node.timestamp=Date.now());return f}},Eb={Re:function(a){if(!a.input.length){var b=null;if(la){var c=Buffer.Qd?Buffer.Qd(256):new Buffer(256),d=0;try{d=pa.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(-1!=f.toString().indexOf("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Db(b,!0)}return a.input.shift()},Ae:function(a,b){null===b||10===b?(ea(za(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ea(za(a.output,0)),a.output=[])}},Fb={Ae:function(a,b){null===b||10===b?(k(za(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(k(za(a.output,0)),a.output=[])}},Q={Fd:null,ud:function(){return Q.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(O.xf(c)||O.isFIFO(c))throw new O.nd(63);Q.Fd||(Q.Fd={dir:{node:{Cd:Q.pd.Cd,xd:Q.pd.xd,lookup:Q.pd.lookup,Gd:Q.pd.Gd,rename:Q.pd.rename,unlink:Q.pd.unlink,rmdir:Q.pd.rmdir,readdir:Q.pd.readdir,symlink:Q.pd.symlink},stream:{zd:Q.qd.zd}},file:{node:{Cd:Q.pd.Cd,xd:Q.pd.xd},stream:{zd:Q.qd.zd,read:Q.qd.read,write:Q.qd.write,Ud:Q.qd.Ud,$d:Q.qd.$d,ce:Q.qd.ce}},link:{node:{Cd:Q.pd.Cd,xd:Q.pd.xd,readlink:Q.pd.readlink},stream:{}},Ie:{node:{Cd:Q.pd.Cd,xd:Q.pd.xd},
stream:O.jf}});c=O.createNode(a,b,c,d);O.vd(c.mode)?(c.pd=Q.Fd.dir.node,c.qd=Q.Fd.dir.stream,c.od={}):O.isFile(c.mode)?(c.pd=Q.Fd.file.node,c.qd=Q.Fd.file.stream,c.td=0,c.od=null):O.Ld(c.mode)?(c.pd=Q.Fd.link.node,c.qd=Q.Fd.link.stream):O.Wd(c.mode)&&(c.pd=Q.Fd.Ie.node,c.qd=Q.Fd.Ie.stream);c.timestamp=Date.now();a&&(a.od[b]=c);return c},Yf:function(a){if(a.od&&a.od.subarray){for(var b=[],c=0;c<a.td;++c)b.push(a.od[c]);return b}return a.od},Zf:function(a){return a.od?a.od.subarray?a.od.subarray(0,
a.td):new Uint8Array(a.od):new Uint8Array(0)},Ne:function(a,b){var c=a.od?a.od.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.od,a.od=new Uint8Array(b),0<a.td&&a.od.set(c.subarray(0,a.td),0))},Jf:function(a,b){if(a.td!=b)if(0==b)a.od=null,a.td=0;else{if(!a.od||a.od.subarray){var c=a.od;a.od=new Uint8Array(b);c&&a.od.set(c.subarray(0,Math.min(b,a.td)))}else if(a.od||(a.od=[]),a.od.length>b)a.od.length=b;else for(;a.od.length<b;)a.od.push(0);a.td=b}},pd:{Cd:function(a){var b=
{};b.dev=O.Wd(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;O.vd(a.mode)?b.size=4096:O.isFile(a.mode)?b.size=a.td:O.Ld(a.mode)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.gf=4096;b.blocks=Math.ceil(b.size/b.gf);return b},xd:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&Q.Jf(a,b.size)},lookup:function(){throw O.qe[44];},Gd:function(a,
b,c,d){return Q.createNode(a,b,c,d)},rename:function(a,b,c){if(O.vd(a.mode)){try{var d=O.Dd(b,c)}catch(g){}if(d)for(var f in d.od)throw new O.nd(55);}delete a.parent.od[a.name];a.name=c;b.od[c]=a;a.parent=b},unlink:function(a,b){delete a.od[b]},rmdir:function(a,b){var c=O.Dd(a,b),d;for(d in c.od)throw new O.nd(55);delete a.od[b]},readdir:function(a){var b=[".",".."],c;for(c in a.od)a.od.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=Q.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!O.Ld(a.mode))throw new O.nd(28);
return a.link}},qd:{read:function(a,b,c,d,f){var g=a.node.od;if(f>=a.node.td)return 0;a=Math.min(a.node.td-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){b.buffer===A.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.od||a.od.subarray)){if(g)return a.od=b.subarray(c,c+d),a.td=d;if(0===a.td&&0===f)return a.od=b.slice(c,c+d),a.td=d;if(f+d<=a.td)return a.od.set(b.subarray(c,c+d),f),d}Q.Ne(a,f+
d);if(a.od.subarray&&b.subarray)a.od.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.od[f+g]=b[c+g];a.td=Math.max(a.td,f+d);return d},zd:function(a,b,c){1===c?b+=a.position:2===c&&O.isFile(a.node.mode)&&(b+=a.node.td);if(0>b)throw new O.nd(28);return b},Ud:function(a,b,c){Q.Ne(a.node,b+c);a.node.td=Math.max(a.node.td,b+c)},$d:function(a,b,c,d,f,g){assert(0===b);if(!O.isFile(a.node.mode))throw new O.nd(43);a=a.node.od;if(g&2||a.buffer!==Ga){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,
d,d+c);d=!0;g=16384*Math.ceil(c/16384);for(b=Da(g);c<g;)A[b+c++]=0;c=b;if(!c)throw new O.nd(48);A.set(a,c)}else d=!1,c=a.byteOffset;return{fg:c,Rf:d}},ce:function(a,b,c,d,f){if(!O.isFile(a.node.mode))throw new O.nd(43);if(f&2)return 0;Q.qd.write(a,b,0,d,c,!1);return 0}}},O={root:null,be:[],Le:{},streams:[],Cf:1,Ed:null,Ke:"/",te:!1,Ve:!0,wd:{},Ze:{Xe:{cf:1,df:2}},nd:null,qe:{},tf:null,he:0,$f:function(a){if(!(a instanceof O.nd)){a:{var b=Error();if(!b.stack){try{throw Error();}catch(c){b=c}if(!b.stack){b=
"(no stack trace available)";break a}}b=b.stack.toString()}e.extraStackTrace&&(b+="\n"+e.extraStackTrace());b=gb(b);throw a+" : "+b;}return ub(a.rd)},sd:function(a,b){a=yb(O.cwd(),a);b=b||{};if(!a)return{path:"",node:null};var c={pe:!0,Ce:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Ce)throw new O.nd(32);a=pb(a.split("/").filter(function(h){return!!h}),!1);var f=O.root;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=O.Dd(f,a[d]);c=tb(c,a[d]);O.Md(f)&&(!g||g&&b.pe)&&
(f=f.ae.root);if(!g||b.Ad)for(g=0;O.Ld(f.mode);)if(f=O.readlink(c),c=yb(rb(c),f),f=O.sd(c,{Ce:b.Ce}).node,40<g++)throw new O.nd(32);}return{path:c,node:f}},Id:function(a){for(var b;;){if(O.ee(a))return a=a.ud.We,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},se:function(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%O.Ed.length},Te:function(a){var b=O.se(a.parent.id,a.name);a.Od=O.Ed[b];O.Ed[b]=a},Ue:function(a){var b=O.se(a.parent.id,a.name);
if(O.Ed[b]===a)O.Ed[b]=a.Od;else for(b=O.Ed[b];b;){if(b.Od===a){b.Od=a.Od;break}b=b.Od}},Dd:function(a,b){var c=O.zf(a);if(c)throw new O.nd(c,a);for(c=O.Ed[O.se(a.id,b)];c;c=c.Od){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return O.lookup(a,b)},createNode:function(a,b,c,d){a=new O.af(a,b,c,d);O.Te(a);return a},oe:function(a){O.Ue(a)},ee:function(a){return a===a.parent},Md:function(a){return!!a.ae},isFile:function(a){return 32768===(a&61440)},vd:function(a){return 16384===(a&61440)},Ld:function(a){return 40960===
(a&61440)},Wd:function(a){return 8192===(a&61440)},xf:function(a){return 24576===(a&61440)},isFIFO:function(a){return 4096===(a&61440)},isSocket:function(a){return 49152===(a&49152)},uf:{r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218},Bf:function(a){var b=O.uf[a];if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b},Oe:function(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},Jd:function(a,
b){if(O.Ve)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0},zf:function(a){var b=O.Jd(a,"x");return b?b:a.pd.lookup?0:2},ze:function(a,b){try{return O.Dd(a,b),20}catch(c){}return O.Jd(a,"wx")},fe:function(a,b,c){try{var d=O.Dd(a,b)}catch(f){return f.rd}if(a=O.Jd(a,"wx"))return a;if(c){if(!O.vd(d.mode))return 54;if(O.ee(d)||O.Id(d)===O.cwd())return 10}else if(O.vd(d.mode))return 31;return 0},Af:function(a,
b){return a?O.Ld(a.mode)?32:O.vd(a.mode)&&("r"!==O.Oe(b)||b&512)?31:O.Jd(a,O.Oe(b)):44},bf:4096,Df:function(a,b){b=b||O.bf;for(a=a||0;a<=b;a++)if(!O.streams[a])return a;throw new O.nd(33);},Pd:function(a){return O.streams[a]},rf:function(a,b,c){O.le||(O.le=function(){},O.le.prototype={object:{get:function(){return this.node},set:function(g){this.node=g}}});var d=new O.le,f;for(f in a)d[f]=a[f];a=d;b=O.Df(b,c);a.fd=b;return O.streams[b]=a},kf:function(a){O.streams[a]=null},jf:{open:function(a){a.qd=
O.wf(a.node.rdev).qd;a.qd.open&&a.qd.open(a)},zd:function(){throw new O.nd(70);}},xe:function(a){return a>>8},bg:function(a){return a&255},Nd:function(a,b){return a<<8|b},De:function(a,b){O.Le[a]={qd:b}},wf:function(a){return O.Le[a]},Qe:function(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.be)}return b},Ye:function(a,b){function c(h){O.he--;return b(h)}function d(h){if(h){if(!d.sf)return d.sf=!0,c(h)}else++g>=f.length&&c(null)}"function"===typeof a&&(b=a,a=!1);O.he++;
1<O.he&&k("warning: "+O.he+" FS.syncfs operations in flight at once, probably just doing extra work");var f=O.Qe(O.root.ud),g=0;f.forEach(function(h){if(!h.type.Ye)return d(null);h.type.Ye(h,a,d)})},ud:function(a,b,c){var d="/"===c,f=!c;if(d&&O.root)throw new O.nd(10);if(!d&&!f){var g=O.sd(c,{pe:!1});c=g.path;g=g.node;if(O.Md(g))throw new O.nd(10);if(!O.vd(g.mode))throw new O.nd(54);}b={type:a,eg:b,We:c,be:[]};a=a.ud(b);a.ud=b;b.root=a;d?O.root=a:g&&(g.ae=b,g.ud&&g.ud.be.push(b));return a},ig:function(a){a=
O.sd(a,{pe:!1});if(!O.Md(a.node))throw new O.nd(28);a=a.node;var b=a.ae,c=O.Qe(b);Object.keys(O.Ed).forEach(function(d){for(d=O.Ed[d];d;){var f=d.Od;-1!==c.indexOf(d.ud)&&O.oe(d);d=f}});a.ae=null;a.ud.be.splice(a.ud.be.indexOf(b),1)},lookup:function(a,b){return a.pd.lookup(a,b)},Gd:function(a,b,c){var d=O.sd(a,{parent:!0}).node;a=sb(a);if(!a||"."===a||".."===a)throw new O.nd(28);var f=O.ze(d,a);if(f)throw new O.nd(f);if(!d.pd.Gd)throw new O.nd(63);return d.pd.Gd(d,a,b,c)},create:function(a,b){return O.Gd(a,
(void 0!==b?b:438)&4095|32768,0)},mkdir:function(a,b){return O.Gd(a,(void 0!==b?b:511)&1023|16384,0)},cg:function(a,b){a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{O.mkdir(c,b)}catch(f){if(20!=f.rd)throw f;}}},ge:function(a,b,c){"undefined"===typeof c&&(c=b,b=438);return O.Gd(a,b|8192,c)},symlink:function(a,b){if(!yb(a))throw new O.nd(44);var c=O.sd(b,{parent:!0}).node;if(!c)throw new O.nd(44);b=sb(b);var d=O.ze(c,b);if(d)throw new O.nd(d);if(!c.pd.symlink)throw new O.nd(63);
return c.pd.symlink(c,b,a)},rename:function(a,b){var c=rb(a),d=rb(b),f=sb(a),g=sb(b);var h=O.sd(a,{parent:!0});var p=h.node;h=O.sd(b,{parent:!0});h=h.node;if(!p||!h)throw new O.nd(44);if(p.ud!==h.ud)throw new O.nd(75);var r=O.Dd(p,f);d=zb(a,d);if("."!==d.charAt(0))throw new O.nd(28);d=zb(b,c);if("."!==d.charAt(0))throw new O.nd(55);try{var q=O.Dd(h,g)}catch(t){}if(r!==q){c=O.vd(r.mode);if(f=O.fe(p,f,c))throw new O.nd(f);if(f=q?O.fe(h,g,c):O.ze(h,g))throw new O.nd(f);if(!p.pd.rename)throw new O.nd(63);
if(O.Md(r)||q&&O.Md(q))throw new O.nd(10);if(h!==p&&(f=O.Jd(p,"w")))throw new O.nd(f);try{O.wd.willMovePath&&O.wd.willMovePath(a,b)}catch(t){k("FS.trackingDelegate['willMovePath']('"+a+"', '"+b+"') threw an exception: "+t.message)}O.Ue(r);try{p.pd.rename(r,h,g)}catch(t){throw t;}finally{O.Te(r)}try{if(O.wd.onMovePath)O.wd.onMovePath(a,b)}catch(t){k("FS.trackingDelegate['onMovePath']('"+a+"', '"+b+"') threw an exception: "+t.message)}}},rmdir:function(a){var b=O.sd(a,{parent:!0}).node,c=sb(a),d=O.Dd(b,
c),f=O.fe(b,c,!0);if(f)throw new O.nd(f);if(!b.pd.rmdir)throw new O.nd(63);if(O.Md(d))throw new O.nd(10);try{O.wd.willDeletePath&&O.wd.willDeletePath(a)}catch(g){k("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.pd.rmdir(b,c);O.oe(d);try{if(O.wd.onDeletePath)O.wd.onDeletePath(a)}catch(g){k("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}},readdir:function(a){a=O.sd(a,{Ad:!0}).node;if(!a.pd.readdir)throw new O.nd(54);return a.pd.readdir(a)},
unlink:function(a){var b=O.sd(a,{parent:!0}).node,c=sb(a),d=O.Dd(b,c),f=O.fe(b,c,!1);if(f)throw new O.nd(f);if(!b.pd.unlink)throw new O.nd(63);if(O.Md(d))throw new O.nd(10);try{O.wd.willDeletePath&&O.wd.willDeletePath(a)}catch(g){k("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.pd.unlink(b,c);O.oe(d);try{if(O.wd.onDeletePath)O.wd.onDeletePath(a)}catch(g){k("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}},readlink:function(a){a=O.sd(a).node;
if(!a)throw new O.nd(44);if(!a.pd.readlink)throw new O.nd(28);return yb(O.Id(a.parent),a.pd.readlink(a))},stat:function(a,b){a=O.sd(a,{Ad:!b}).node;if(!a)throw new O.nd(44);if(!a.pd.Cd)throw new O.nd(63);return a.pd.Cd(a)},lstat:function(a){return O.stat(a,!0)},chmod:function(a,b,c){var d;"string"===typeof a?d=O.sd(a,{Ad:!c}).node:d=a;if(!d.pd.xd)throw new O.nd(63);d.pd.xd(d,{mode:b&4095|d.mode&-4096,timestamp:Date.now()})},lchmod:function(a,b){O.chmod(a,b,!0)},fchmod:function(a,b){a=O.Pd(a);if(!a)throw new O.nd(8);
O.chmod(a.node,b)},chown:function(a,b,c,d){var f;"string"===typeof a?f=O.sd(a,{Ad:!d}).node:f=a;if(!f.pd.xd)throw new O.nd(63);f.pd.xd(f,{timestamp:Date.now()})},lchown:function(a,b,c){O.chown(a,b,c,!0)},fchown:function(a,b,c){a=O.Pd(a);if(!a)throw new O.nd(8);O.chown(a.node,b,c)},truncate:function(a,b){if(0>b)throw new O.nd(28);var c;"string"===typeof a?c=O.sd(a,{Ad:!0}).node:c=a;if(!c.pd.xd)throw new O.nd(63);if(O.vd(c.mode))throw new O.nd(31);if(!O.isFile(c.mode))throw new O.nd(28);if(a=O.Jd(c,
"w"))throw new O.nd(a);c.pd.xd(c,{size:b,timestamp:Date.now()})},Xf:function(a,b){a=O.Pd(a);if(!a)throw new O.nd(8);if(0===(a.flags&2097155))throw new O.nd(28);O.truncate(a.node,b)},jg:function(a,b,c){a=O.sd(a,{Ad:!0}).node;a.pd.xd(a,{timestamp:Math.max(b,c)})},open:function(a,b,c,d,f){if(""===a)throw new O.nd(44);b="string"===typeof b?O.Bf(b):b;c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=qb(a);try{g=O.sd(a,{Ad:!(b&131072)}).node}catch(p){}}var h=!1;if(b&
64)if(g){if(b&128)throw new O.nd(20);}else g=O.Gd(a,c,0),h=!0;if(!g)throw new O.nd(44);O.Wd(g.mode)&&(b&=-513);if(b&65536&&!O.vd(g.mode))throw new O.nd(54);if(!h&&(c=O.Af(g,b)))throw new O.nd(c);b&512&&O.truncate(g,0);b&=-131713;d=O.rf({node:g,path:O.Id(g),flags:b,seekable:!0,position:0,qd:g.qd,Qf:[],error:!1},d,f);d.qd.open&&d.qd.open(d);!e.logReadFiles||b&1||(O.Be||(O.Be={}),a in O.Be||(O.Be[a]=1,k("FS.trackingDelegate error on read file: "+a)));try{O.wd.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=O.Ze.Xe.cf),
0!==(b&2097155)&&(f|=O.Ze.Xe.df),O.wd.onOpenFile(a,f))}catch(p){k("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+p.message)}return d},close:function(a){if(O.Xd(a))throw new O.nd(8);a.Kd&&(a.Kd=null);try{a.qd.close&&a.qd.close(a)}catch(b){throw b;}finally{O.kf(a.fd)}a.fd=null},Xd:function(a){return null===a.fd},zd:function(a,b,c){if(O.Xd(a))throw new O.nd(8);if(!a.seekable||!a.qd.zd)throw new O.nd(70);if(0!=c&&1!=c&&2!=c)throw new O.nd(28);a.position=a.qd.zd(a,b,c);a.Qf=[];
return a.position},read:function(a,b,c,d,f){if(0>d||0>f)throw new O.nd(28);if(O.Xd(a))throw new O.nd(8);if(1===(a.flags&2097155))throw new O.nd(8);if(O.vd(a.node.mode))throw new O.nd(31);if(!a.qd.read)throw new O.nd(28);var g="undefined"!==typeof f;if(!g)f=a.position;else if(!a.seekable)throw new O.nd(70);b=a.qd.read(a,b,c,d,f);g||(a.position+=b);return b},write:function(a,b,c,d,f,g){if(0>d||0>f)throw new O.nd(28);if(O.Xd(a))throw new O.nd(8);if(0===(a.flags&2097155))throw new O.nd(8);if(O.vd(a.node.mode))throw new O.nd(31);
if(!a.qd.write)throw new O.nd(28);a.seekable&&a.flags&1024&&O.zd(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new O.nd(70);b=a.qd.write(a,b,c,d,f,g);h||(a.position+=b);try{if(a.path&&O.wd.onWriteToFile)O.wd.onWriteToFile(a.path)}catch(p){k("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+p.message)}return b},Ud:function(a,b,c){if(O.Xd(a))throw new O.nd(8);if(0>b||0>=c)throw new O.nd(28);if(0===(a.flags&2097155))throw new O.nd(8);if(!O.isFile(a.node.mode)&&
!O.vd(a.node.mode))throw new O.nd(43);if(!a.qd.Ud)throw new O.nd(138);a.qd.Ud(a,b,c)},$d:function(a,b,c,d,f,g){if(0!==(f&2)&&0===(g&2)&&2!==(a.flags&2097155))throw new O.nd(2);if(1===(a.flags&2097155))throw new O.nd(2);if(!a.qd.$d)throw new O.nd(43);return a.qd.$d(a,b,c,d,f,g)},ce:function(a,b,c,d,f){return a&&a.qd.ce?a.qd.ce(a,b,c,d,f):0},dg:function(){return 0},ue:function(a,b,c){if(!a.qd.ue)throw new O.nd(59);return a.qd.ue(a,b,c)},readFile:function(a,b){b=b||{};b.flags=b.flags||"r";b.encoding=
b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,d=O.open(a,b.flags);a=O.stat(a).size;var f=new Uint8Array(a);O.read(d,f,0,a,0);"utf8"===b.encoding?c=za(f,0):"binary"===b.encoding&&(c=f);O.close(d);return c},writeFile:function(a,b,c){c=c||{};c.flags=c.flags||"w";a=O.open(a,c.flags,c.mode);if("string"===typeof b){var d=new Uint8Array(Ba(b)+1);b=Aa(b,d,0,d.length);O.write(a,d,0,b,void 0,c.hf)}else if(ArrayBuffer.isView(b))O.write(a,
b,0,b.byteLength,void 0,c.hf);else throw Error("Unsupported data type");O.close(a)},cwd:function(){return O.Ke},chdir:function(a){a=O.sd(a,{Ad:!0});if(null===a.node)throw new O.nd(44);if(!O.vd(a.node.mode))throw new O.nd(54);var b=O.Jd(a.node,"x");if(b)throw new O.nd(b);O.Ke=a.path},mf:function(){O.mkdir("/tmp");O.mkdir("/home");O.mkdir("/home/web_user")},lf:function(){O.mkdir("/dev");O.De(O.Nd(1,3),{read:function(){return 0},write:function(b,c,d,f){return f}});O.ge("/dev/null",O.Nd(1,3));Bb(O.Nd(5,
0),Eb);Bb(O.Nd(6,0),Fb);O.ge("/dev/tty",O.Nd(5,0));O.ge("/dev/tty1",O.Nd(6,0));var a=xb();O.Hd("/dev","random",a);O.Hd("/dev","urandom",a);O.mkdir("/dev/shm");O.mkdir("/dev/shm/tmp")},pf:function(){O.mkdir("/proc");O.mkdir("/proc/self");O.mkdir("/proc/self/fd");O.ud({ud:function(){var a=O.createNode("/proc/self","fd",16895,73);a.pd={lookup:function(b,c){var d=O.Pd(+c);if(!d)throw new O.nd(8);b={parent:null,ud:{We:"fake"},pd:{readlink:function(){return d.path}}};return b.parent=b}};return a}},{},"/proc/self/fd")},
qf:function(){e.stdin?O.Hd("/dev","stdin",e.stdin):O.symlink("/dev/tty","/dev/stdin");e.stdout?O.Hd("/dev","stdout",null,e.stdout):O.symlink("/dev/tty","/dev/stdout");e.stderr?O.Hd("/dev","stderr",null,e.stderr):O.symlink("/dev/tty1","/dev/stderr");O.open("/dev/stdin","r");O.open("/dev/stdout","w");O.open("/dev/stderr","w")},Me:function(){O.nd||(O.nd=function(a,b){this.node=b;this.Kf=function(c){this.rd=c};this.Kf(a);this.message="FS error"},O.nd.prototype=Error(),O.nd.prototype.constructor=O.nd,
[44].forEach(function(a){O.qe[a]=new O.nd(a);O.qe[a].stack="<generic error, no stack>"}))},Lf:function(){O.Me();O.Ed=Array(4096);O.ud(Q,{},"/");O.mf();O.lf();O.pf();O.tf={MEMFS:Q}},Vd:function(a,b,c){O.Vd.te=!0;O.Me();e.stdin=a||e.stdin;e.stdout=b||e.stdout;e.stderr=c||e.stderr;O.qf()},quit:function(){O.Vd.te=!1;var a=e._fflush;a&&a(0);for(a=0;a<O.streams.length;a++){var b=O.streams[a];b&&O.close(b)}},re:function(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c},Wf:function(a,b){a=O.me(a,b);if(a.exists)return a.object;
ub(a.error);return null},me:function(a,b){try{var c=O.sd(a,{Ad:!b});a=c.path}catch(f){}var d={ee:!1,exists:!1,error:0,name:null,path:null,object:null,Ff:!1,Hf:null,Gf:null};try{c=O.sd(a,{parent:!0}),d.Ff=!0,d.Hf=c.path,d.Gf=c.node,d.name=sb(a),c=O.sd(a,{Ad:!b}),d.exists=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.ee="/"===c.path}catch(f){d.error=f.rd}return d},Uf:function(a,b){a="string"===typeof a?a:O.Id(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=tb(a,c);try{O.mkdir(d)}catch(f){}a=
d}}return d},nf:function(a,b,c,d,f){a=tb("string"===typeof a?a:O.Id(a),b);return O.create(a,O.re(d,f))},Je:function(a,b,c,d,f,g){a=b?tb("string"===typeof a?a:O.Id(a),b):a;d=O.re(d,f);f=O.create(a,d);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}O.chmod(f,d|146);a=O.open(f,"w");O.write(a,c,0,c.length,0,g);O.close(a);O.chmod(f,d)}return f},Hd:function(a,b,c,d){a=tb("string"===typeof a?a:O.Id(a),b);b=O.re(!!c,!!d);O.Hd.xe||(O.Hd.xe=64);var f=
O.Nd(O.Hd.xe++,0);O.De(f,{open:function(g){g.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(g,h,p,r){for(var q=0,t=0;t<r;t++){try{var x=c()}catch(E){throw new O.nd(29);}if(void 0===x&&0===q)throw new O.nd(6);if(null===x||void 0===x)break;q++;h[p+t]=x}q&&(g.node.timestamp=Date.now());return q},write:function(g,h,p,r){for(var q=0;q<r;q++)try{d(h[p+q])}catch(t){throw new O.nd(29);}r&&(g.node.timestamp=Date.now());return q}});return O.ge(a,b,f)},Pe:function(a){if(a.ve||
a.yf||a.link||a.od)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(na)try{a.od=Db(na(a.url),!0),a.td=a.od.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||ub(29);return b},Tf:function(a,b,c,d,f){function g(){this.we=!1;this.Qd=[]}g.prototype.get=
function(q){if(!(q>this.length-1||0>q)){var t=q%this.chunkSize;return this.Se(q/this.chunkSize|0)[t]}};g.prototype.Ef=function(q){this.Se=q};g.prototype.He=function(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+c+". Status: "+q.status);var t=Number(q.getResponseHeader("Content-length")),x,E=(x=q.getResponseHeader("Accept-Ranges"))&&"bytes"===x;q=(x=q.getResponseHeader("Content-Encoding"))&&"gzip"===x;var n=
1048576;E||(n=t);var u=this;u.Ef(function(z){var K=z*n,P=(z+1)*n-1;P=Math.min(P,t-1);if("undefined"===typeof u.Qd[z]){var ob=u.Qd;if(K>P)throw Error("invalid range ("+K+", "+P+") or no bytes requested!");if(P>t-1)throw Error("only "+t+" bytes available! programmer error!");var C=new XMLHttpRequest;C.open("GET",c,!1);t!==n&&C.setRequestHeader("Range","bytes="+K+"-"+P);"undefined"!=typeof Uint8Array&&(C.responseType="arraybuffer");C.overrideMimeType&&C.overrideMimeType("text/plain; charset=x-user-defined");
C.send(null);if(!(200<=C.status&&300>C.status||304===C.status))throw Error("Couldn't load "+c+". Status: "+C.status);K=void 0!==C.response?new Uint8Array(C.response||[]):Db(C.responseText||"",!0);ob[z]=K}if("undefined"===typeof u.Qd[z])throw Error("doXHR failed!");return u.Qd[z]});if(q||!t)n=t=1,n=t=this.Se(0).length,ea("LazyFiles on gzip forces download of the whole file when length is accessed");this.ff=t;this.ef=n;this.we=!0};if("undefined"!==typeof XMLHttpRequest){if(!m)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var h=new g;Object.defineProperties(h,{length:{get:function(){this.we||this.He();return this.ff}},chunkSize:{get:function(){this.we||this.He();return this.ef}}});h={ve:!1,od:h}}else h={ve:!1,url:c};var p=O.nf(a,b,h,d,f);h.od?p.od=h.od:h.url&&(p.od=null,p.url=h.url);Object.defineProperties(p,{td:{get:function(){return this.od.length}}});var r={};Object.keys(p.qd).forEach(function(q){var t=p.qd[q];r[q]=function(){if(!O.Pe(p))throw new O.nd(29);return t.apply(null,arguments)}});r.read=function(q,t,x,
E,n){if(!O.Pe(p))throw new O.nd(29);q=q.node.od;if(n>=q.length)return 0;E=Math.min(q.length-n,E);if(q.slice)for(var u=0;u<E;u++)t[x+u]=q[n+u];else for(u=0;u<E;u++)t[x+u]=q.get(n+u);return E};p.qd=r;return p},Vf:function(a,b,c,d,f,g,h,p,r,q){function t(E){function n(z){q&&q();p||O.Je(a,b,z,d,f,r);g&&g();Xa()}var u=!1;e.preloadPlugins.forEach(function(z){!u&&z.canHandle(x)&&(z.handle(E,x,n,function(){h&&h();Xa()}),u=!0)});u||n(E)}Gb.Vd();var x=b?yb(tb(a,b)):a;Wa();"string"==typeof c?Gb.Sf(c,function(E){t(E)},
h):t(c)},indexedDB:function(){return window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB},Ee:function(){return"EM_FS_"+window.location.pathname},Fe:20,Td:"FILE_DATA",gg:function(a,b,c){b=b||function(){};c=c||function(){};var d=O.indexedDB();try{var f=d.open(O.Ee(),O.Fe)}catch(g){return c(g)}f.onupgradeneeded=function(){ea("creating db");f.result.createObjectStore(O.Td)};f.onsuccess=function(){var g=f.result.transaction([O.Td],"readwrite"),h=g.objectStore(O.Td),p=0,r=
0,q=a.length;a.forEach(function(t){t=h.put(O.me(t).object.od,t);t.onsuccess=function(){p++;p+r==q&&(0==r?b():c())};t.onerror=function(){r++;p+r==q&&(0==r?b():c())}});g.onerror=c};f.onerror=c},ag:function(a,b,c){b=b||function(){};c=c||function(){};var d=O.indexedDB();try{var f=d.open(O.Ee(),O.Fe)}catch(g){return c(g)}f.onupgradeneeded=c;f.onsuccess=function(){var g=f.result;try{var h=g.transaction([O.Td],"readonly")}catch(x){c(x);return}var p=h.objectStore(O.Td),r=0,q=0,t=a.length;a.forEach(function(x){var E=
p.get(x);E.onsuccess=function(){O.me(x).exists&&O.unlink(x);O.Je(rb(x),sb(x),E.result,!0,!0,!0);r++;r+q==t&&(0==q?b():c())};E.onerror=function(){q++;r+q==t&&(0==q?b():c())}});h.onerror=c};f.onerror=c}};
function Hb(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&qb(b)!==qb(O.Id(f.node)))return-54;throw f;}H[c>>2]=d.dev;H[c+4>>2]=0;H[c+8>>2]=d.ino;H[c+12>>2]=d.mode;H[c+16>>2]=d.nlink;H[c+20>>2]=d.uid;H[c+24>>2]=d.gid;H[c+28>>2]=d.rdev;H[c+32>>2]=0;N=[d.size>>>0,(L=d.size,1<=+Math.abs(L)?0<L?(Math.min(+Math.floor(L/4294967296),4294967295)|0)>>>0:~~+Math.ceil((L-+(~~L>>>0))/4294967296)>>>0:0)];H[c+40>>2]=N[0];H[c+44>>2]=N[1];H[c+48>>2]=4096;H[c+52>>2]=d.blocks;H[c+56>>2]=d.atime.getTime()/1E3|0;H[c+60>>
2]=0;H[c+64>>2]=d.mtime.getTime()/1E3|0;H[c+68>>2]=0;H[c+72>>2]=d.ctime.getTime()/1E3|0;H[c+76>>2]=0;N=[d.ino>>>0,(L=d.ino,1<=+Math.abs(L)?0<L?(Math.min(+Math.floor(L/4294967296),4294967295)|0)>>>0:~~+Math.ceil((L-+(~~L>>>0))/4294967296)>>>0:0)];H[c+80>>2]=N[0];H[c+84>>2]=N[1];return 0}var Ib=void 0;function Jb(){Ib+=4;return H[Ib-4>>2]}function R(a){a=O.Pd(a);if(!a)throw new O.nd(8);return a}function Kb(){void 0===Kb.start&&(Kb.start=Date.now());return 1E3*(Date.now()-Kb.start)|0}var Lb;
la?Lb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Lb=dateNow:Lb=function(){return performance.now()};var Mb=1,Nb=[],S=[],Ob=[],Pb=[],Qb=[],T=[],U=[],Rb=[],V=[],Sb={},Tb={},Ub=4;function W(a){Vb||(Vb=a)}function Wb(a){for(var b=Mb++,c=a.length;c<b;c++)a[c]=null;return b}var Vb,Xb=[];function Yb(a,b,c,d){for(var f=0;f<a;f++){var g=X[c](),h=g&&Wb(d);g?(g.name=h,d[h]=g):W(1282);H[b+4*f>>2]=h}}
function Zb(a,b,c,d,f,g,h,p){b=S[b];if(a=X[a](b,c))d=p&&y(a.name,p,d),f&&(H[f>>2]=d),g&&(H[g>>2]=a.size),h&&(H[h>>2]=a.type)}function $b(a,b){Ja[a>>2]=b;Ja[a+4>>2]=(b-Ja[a>>2])/4294967296}
function ac(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&W(1280);return;case 36345:d=0;break;case 34466:var f=X.getParameter(34467);d=f?f.length:0}if(void 0===d)switch(f=X.getParameter(a),typeof f){case "number":d=f;break;case "boolean":d=f?1:0;break;case "string":W(1280);return;case "object":if(null===f)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:W(1280);return}else{if(f instanceof Float32Array||
f instanceof Uint32Array||f instanceof Int32Array||f instanceof Array){for(a=0;a<f.length;++a)switch(c){case 0:H[b+4*a>>2]=f[a];break;case 2:I[b+4*a>>2]=f[a];break;case 4:A[b+a>>0]=f[a]?1:0}return}try{d=f.name|0}catch(g){W(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:W(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+f+" of type "+typeof f+"!");return}switch(c){case 1:$b(b,
d);break;case 0:H[b>>2]=d;break;case 2:I[b>>2]=d;break;case 4:A[b>>0]=d?1:0}}else W(1281)}function bc(a){var b=Ba(a)+1,c=Da(b);y(a,c,b);return c}function cc(a,b,c,d){if(c)if(a=X.getUniform(S[a],T[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:H[c>>2]=a;break;case 2:I[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:H[c+4*b>>2]=a[b];break;case 2:I[c+4*b>>2]=a[b]}else W(1281)}
function dc(a,b,c,d){if(c)if(a=X.getVertexAttrib(a,b),34975==b)H[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:H[c>>2]=a;break;case 2:I[c>>2]=a;break;case 5:H[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:H[c+4*b>>2]=a[b];break;case 2:I[c+4*b>>2]=a[b];break;case 5:H[c+4*b>>2]=Math.fround(a[b])}else W(1281)}
function ec(a,b,c,d,f){a-=5120;a=1==a?G:4==a?H:6==a?I:5==a||28922==a?Ja:Ia;var g=31-Math.clz32(a.BYTES_PER_ELEMENT),h=Ub;return a.subarray(f>>g,f+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<g)+h-1&-h)>>g)}var fc=[],hc=[],ic={};
function jc(){if(!kc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ia||"./this.program"},b;for(b in ic)a[b]=ic[b];var c=[];for(b in a)c.push(b+"="+a[b]);kc=c}return kc}var kc;function lc(a){return 0===a%4&&(0!==a%100||0===a%400)}function mc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var nc=[31,29,31,30,31,30,31,31,30,31,30,31],oc=[31,28,31,30,31,30,31,31,30,31,30,31];function pc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(lc(a.getFullYear())?nc:oc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function qc(a,b,c,d){a||(a=this);this.parent=a;this.ud=a.ud;this.ae=null;this.id=O.Cf++;this.name=b;this.mode=c;this.pd={};this.qd={};this.rdev=d}Object.defineProperties(qc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},yf:{get:function(){return O.vd(this.mode)}},ve:{get:function(){return O.Wd(this.mode)}}});O.af=qc;O.Lf();
for(var Gb,X,Y=0;32>Y;++Y)Xb.push(Array(Y));var rc=new Float32Array(288);for(Y=0;288>Y;++Y)fc[Y]=rc.subarray(0,Y+1);var sc=new Int32Array(288);for(Y=0;288>Y;++Y)hc[Y]=sc.subarray(0,Y+1);function Db(a,b){var c=Array(Ba(a)+1);a=Aa(a,c,0,c.length);b&&(c.length=a);return c}Oa.push({vf:function(){tc()}});
var Cc={b:function(a,b,c,d){w("Assertion failed: "+D(a)+", at: "+[b?D(b):"unknown filename",c,d?D(d):"unknown function"])},Ca:function(a,b){return hb(a,b)},Ba:function(a,b){return nb(a,b)},Pa:function(a,b,c,d){try{for(var f=0,g=b?H[b>>2]:0,h=b?H[b+4>>2]:0,p=c?H[c>>2]:0,r=c?H[c+4>>2]:0,q=d?H[d>>2]:0,t=d?H[d+4>>2]:0,x=0,E=0,n=0,u=0,z=0,K=0,P=(b?H[b>>2]:0)|(c?H[c>>2]:0)|(d?H[d>>2]:0),ob=(b?H[b+4>>2]:0)|(c?H[c+4>>2]:0)|(d?H[d+4>>2]:0),C=0;C<a;C++){var M=1<<C%32;if(32>C?P&M:ob&M){var cb=O.Pd(C);if(!cb)throw new O.nd(8);
var db=5;cb.qd.If&&(db=cb.qd.If(cb));db&1&&(32>C?g&M:h&M)&&(32>C?x|=M:E|=M,f++);db&4&&(32>C?p&M:r&M)&&(32>C?n|=M:u|=M,f++);db&2&&(32>C?q&M:t&M)&&(32>C?z|=M:K|=M,f++)}}b&&(H[b>>2]=x,H[b+4>>2]=E);c&&(H[c>>2]=n,H[c+4>>2]=u);d&&(H[d>>2]=z,H[d+4>>2]=K);return f}catch(wb){return"undefined"!==typeof O&&wb instanceof O.nd||w(wb),-wb.rd}},Ia:function(a,b){try{a=D(a);if(b&-8)var c=-28;else{var d;(d=O.sd(a,{Ad:!0}).node)?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&O.Jd(d,a)?-2:0):c=-44}return c}catch(f){return"undefined"!==
typeof O&&f instanceof O.nd||w(f),-f.rd}},n:function(a,b,c){Ib=c;try{var d=R(a);switch(b){case 0:var f=Jb();return 0>f?-28:O.open(d.path,d.flags,0,f).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=Jb(),d.flags|=f,0;case 12:return f=Jb(),Ha[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return ub(28),-1;default:return-28}}catch(g){return"undefined"!==typeof O&&g instanceof O.nd||w(g),-g.rd}},Ra:function(a,b){try{var c=R(a);return Hb(O.stat,c.path,b)}catch(d){return"undefined"!==
typeof O&&d instanceof O.nd||w(d),-d.rd}},Oa:function(a,b,c){try{var d=R(a);d.Kd||(d.Kd=O.readdir(d.path));a=0;for(var f=O.zd(d,0,1),g=Math.floor(f/280);g<d.Kd.length&&a+280<=c;){var h=d.Kd[g];if("."===h[0]){var p=1;var r=4}else{var q=O.Dd(d.node,h);p=q.id;r=O.Wd(q.mode)?2:O.vd(q.mode)?4:O.Ld(q.mode)?10:8}N=[p>>>0,(L=p,1<=+Math.abs(L)?0<L?(Math.min(+Math.floor(L/4294967296),4294967295)|0)>>>0:~~+Math.ceil((L-+(~~L>>>0))/4294967296)>>>0:0)];H[b+a>>2]=N[0];H[b+a+4>>2]=N[1];N=[280*(g+1)>>>0,(L=280*(g+
1),1<=+Math.abs(L)?0<L?(Math.min(+Math.floor(L/4294967296),4294967295)|0)>>>0:~~+Math.ceil((L-+(~~L>>>0))/4294967296)>>>0:0)];H[b+a+8>>2]=N[0];H[b+a+12>>2]=N[1];Ha[b+a+16>>1]=280;A[b+a+18>>0]=r;y(h,b+a+19,256);a+=280;g+=1}O.zd(d,280*g,0);return a}catch(t){return"undefined"!==typeof O&&t instanceof O.nd||w(t),-t.rd}},Ka:function(a,b){try{return uc(b,0,136),H[b>>2]=1,H[b+4>>2]=2,H[b+8>>2]=3,H[b+12>>2]=4,0}catch(c){return"undefined"!==typeof O&&c instanceof O.nd||w(c),-c.rd}},q:function(a,b,c){Ib=c;
try{var d=R(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=Jb();return H[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:return f=Jb(),O.ue(d,b,f);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:w("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof O&&g instanceof O.nd||w(g),-g.rd}},Sa:function(a,b){try{return a=D(a),Hb(O.lstat,a,b)}catch(c){return"undefined"!==
typeof O&&c instanceof O.nd||w(c),-c.rd}},r:function(a,b,c){Ib=c;try{var d=D(a),f=Jb();return O.open(d,b,f).fd}catch(g){return"undefined"!==typeof O&&g instanceof O.nd||w(g),-g.rd}},Ma:function(a,b,c,d){try{return d&&(H[d>>2]=-1,H[d+4>>2]=-1,H[d+8>>2]=-1,H[d+12>>2]=-1),0}catch(f){return"undefined"!==typeof O&&f instanceof O.nd||w(f),-f.rd}},Ha:function(a,b,c){try{var d=R(a);return O.read(d,A,b,c)}catch(f){return"undefined"!==typeof O&&f instanceof O.nd||w(f),-f.rd}},Da:function(a,b){try{return a=
D(a),b=D(b),O.rename(a,b),0}catch(c){return"undefined"!==typeof O&&c instanceof O.nd||w(c),-c.rd}},Ja:function(a){try{return a=D(a),O.rmdir(a),0}catch(b){return"undefined"!==typeof O&&b instanceof O.nd||w(b),-b.rd}},La:function(){return 0},Qa:function(a,b){try{return a=D(a),Hb(O.stat,a,b)}catch(c){return"undefined"!==typeof O&&c instanceof O.nd||w(c),-c.rd}},Ga:function(a){try{return a=D(a),O.unlink(a),0}catch(b){return"undefined"!==typeof O&&b instanceof O.nd||w(b),-b.rd}},c:function(){w()},ua:Kb,
Na:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Lb();else return ub(28),-1;H[b>>2]=a/1E3|0;H[b+4>>2]=a%1E3*1E6|0;return 0},ca:function(a){X.activeTexture(a)},ba:function(a,b){X.attachShader(S[a],U[b])},sa:function(a,b){X.Bd.beginQueryEXT(a,V[b])},aa:function(a,b,c){X.bindAttribLocation(S[a],b,D(c))},_:function(a,b){X.bindBuffer(a,Nb[b])},Z:function(a,b){X.bindFramebuffer(a,Ob[b])},Y:function(a,b){X.bindRenderbuffer(a,Pb[b])},X:function(a,b){X.bindTexture(a,Qb[b])},ka:function(a){X.bindVertexArray(Rb[a])},
W:function(a,b,c,d){X.blendColor(a,b,c,d)},V:function(a){X.blendEquation(a)},U:function(a,b){X.blendEquationSeparate(a,b)},T:function(a,b){X.blendFunc(a,b)},S:function(a,b,c,d){X.blendFuncSeparate(a,b,c,d)},R:function(a,b,c,d){X.bufferData(a,c?G.subarray(c,c+b):b,d)},P:function(a,b,c,d){X.bufferSubData(a,b,G.subarray(d,d+c))},O:function(a){return X.checkFramebufferStatus(a)},N:function(a){X.clear(a)},M:function(a,b,c,d){X.clearColor(a,b,c,d)},L:function(a){X.clearDepth(a)},K:function(a){X.clearStencil(a)},
J:function(a,b,c,d){X.colorMask(!!a,!!b,!!c,!!d)},I:function(a){X.compileShader(U[a])},H:function(a,b,c,d,f,g,h,p){X.compressedTexImage2D(a,b,c,d,f,g,p?G.subarray(p,p+h):null)},G:function(a,b,c,d,f,g,h,p,r){X.compressedTexSubImage2D(a,b,c,d,f,g,h,r?G.subarray(r,r+p):null)},E:function(a,b,c,d,f,g,h,p){X.copyTexImage2D(a,b,c,d,f,g,h,p)},D:function(a,b,c,d,f,g,h,p){X.copyTexSubImage2D(a,b,c,d,f,g,h,p)},C:function(){var a=Wb(S),b=X.createProgram();b.name=a;S[a]=b;return a},B:function(a){var b=Wb(U);U[b]=
X.createShader(a);return b},A:function(a){X.cullFace(a)},z:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],f=Nb[d];f&&(X.deleteBuffer(f),f.name=0,Nb[d]=null)}},y:function(a,b){for(var c=0;c<a;++c){var d=H[b+4*c>>2],f=Ob[d];f&&(X.deleteFramebuffer(f),f.name=0,Ob[d]=null)}},x:function(a){if(a){var b=S[a];b?(X.deleteProgram(b),b.name=0,S[a]=null,Sb[a]=null):W(1281)}},va:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],f=V[d];f&&(X.Bd.deleteQueryEXT(f),V[d]=null)}},w:function(a,b){for(var c=
0;c<a;c++){var d=H[b+4*c>>2],f=Pb[d];f&&(X.deleteRenderbuffer(f),f.name=0,Pb[d]=null)}},v:function(a){if(a){var b=U[a];b?(X.deleteShader(b),U[a]=null):W(1281)}},Yc:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2],f=Qb[d];f&&(X.deleteTexture(f),f.name=0,Qb[d]=null)}},ja:function(a,b){for(var c=0;c<a;c++){var d=H[b+4*c>>2];X.deleteVertexArray(Rb[d]);Rb[d]=null}},Xc:function(a){X.depthFunc(a)},Wc:function(a){X.depthMask(!!a)},Vc:function(a,b){X.depthRange(a,b)},Uc:function(a,b){X.detachShader(S[a],
U[b])},Tc:function(a){X.disable(a)},Sc:function(a){X.disableVertexAttribArray(a)},Rc:function(a,b,c){X.drawArrays(a,b,c)},fa:function(a,b,c,d){X.drawArraysInstanced(a,b,c,d)},ga:function(a,b){for(var c=Xb[a],d=0;d<a;d++)c[d]=H[b+4*d>>2];X.drawBuffers(c)},Qc:function(a,b,c,d){X.drawElements(a,b,c,d)},ea:function(a,b,c,d,f){X.drawElementsInstanced(a,b,c,d,f)},Pc:function(a){X.enable(a)},Oc:function(a){X.enableVertexAttribArray(a)},ra:function(a){X.Bd.endQueryEXT(a)},Nc:function(){X.finish()},Mc:function(){X.flush()},
Lc:function(a,b,c,d){X.framebufferRenderbuffer(a,b,c,Pb[d])},Kc:function(a,b,c,d,f){X.framebufferTexture2D(a,b,c,Qb[d],f)},Jc:function(a){X.frontFace(a)},Ic:function(a,b){Yb(a,b,"createBuffer",Nb)},Gc:function(a,b){Yb(a,b,"createFramebuffer",Ob)},wa:function(a,b){for(var c=0;c<a;c++){var d=X.Bd.createQueryEXT();if(!d){for(W(1282);c<a;)H[b+4*c++>>2]=0;break}var f=Wb(V);d.name=f;V[f]=d;H[b+4*c>>2]=f}},Fc:function(a,b){Yb(a,b,"createRenderbuffer",Pb)},Ec:function(a,b){Yb(a,b,"createTexture",Qb)},ia:function(a,
b){Yb(a,b,"createVertexArray",Rb)},Hc:function(a){X.generateMipmap(a)},Dc:function(a,b,c,d,f,g,h){Zb("getActiveAttrib",a,b,c,d,f,g,h)},Cc:function(a,b,c,d,f,g,h){Zb("getActiveUniform",a,b,c,d,f,g,h)},Bc:function(a,b,c,d){a=X.getAttachedShaders(S[a]);var f=a.length;f>b&&(f=b);H[c>>2]=f;for(b=0;b<f;++b)H[d+4*b>>2]=U.indexOf(a[b])},Ac:function(a,b){return X.getAttribLocation(S[a],D(b))},zc:function(a,b){ac(a,b,4)},yc:function(a,b,c){c?H[c>>2]=X.getBufferParameter(a,b):W(1281)},xc:function(){var a=X.getError()||
Vb;Vb=0;return a},wc:function(a,b){ac(a,b,2)},vc:function(a,b,c,d){a=X.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;H[d>>2]=a},uc:function(a,b){ac(a,b,0)},sc:function(a,b,c,d){a=X.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?y(a,d,b):0;c&&(H[c>>2]=b)},tc:function(a,b,c){if(c)if(a>=Mb)W(1281);else{var d=Sb[a];if(d)if(35716==b)a=X.getProgramInfoLog(S[a]),null===a&&(a="(unknown error)"),H[c>>2]=a.length+1;else if(35719==
b)H[c>>2]=d.ye;else if(35722==b){if(-1==d.Yd){a=S[a];var f=X.getProgramParameter(a,35721);for(b=d.Yd=0;b<f;++b)d.Yd=Math.max(d.Yd,X.getActiveAttrib(a,b).name.length+1)}H[c>>2]=d.Yd}else if(35381==b){if(-1==d.Zd)for(a=S[a],f=X.getProgramParameter(a,35382),b=d.Zd=0;b<f;++b)d.Zd=Math.max(d.Zd,X.getActiveUniformBlockName(a,b).length+1);H[c>>2]=d.Zd}else H[c>>2]=X.getProgramParameter(S[a],b);else W(1282)}else W(1281)},ma:function(a,b,c){if(c){a=X.Bd.getQueryObjectEXT(V[a],b);var d;"boolean"==typeof a?
d=a?1:0:d=a;$b(c,d)}else W(1281)},oa:function(a,b,c){if(c){a=X.Bd.getQueryObjectEXT(V[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;H[c>>2]=d}else W(1281)},la:function(a,b,c){if(c){a=X.Bd.getQueryObjectEXT(V[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;$b(c,d)}else W(1281)},na:function(a,b,c){if(c){a=X.Bd.getQueryObjectEXT(V[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;H[c>>2]=d}else W(1281)},pa:function(a,b,c){c?H[c>>2]=X.Bd.getQueryEXT(a,b):W(1281)},rc:function(a,b,c){c?H[c>>2]=X.getRenderbufferParameter(a,
b):W(1281)},pc:function(a,b,c,d){a=X.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?y(a,d,b):0;c&&(H[c>>2]=b)},oc:function(a,b,c,d){a=X.getShaderPrecisionFormat(a,b);H[c>>2]=a.rangeMin;H[c+4>>2]=a.rangeMax;H[d>>2]=a.precision},nc:function(a,b,c,d){if(a=X.getShaderSource(U[a]))b=0<b&&d?y(a,d,b):0,c&&(H[c>>2]=b)},qc:function(a,b,c){c?35716==b?(a=X.getShaderInfoLog(U[a]),null===a&&(a="(unknown error)"),H[c>>2]=a?a.length+1:0):35720==b?(a=X.getShaderSource(U[a]),H[c>>2]=a?a.length+1:
0):H[c>>2]=X.getShaderParameter(U[a],b):W(1281)},mc:function(a){if(Tb[a])return Tb[a];switch(a){case 7939:var b=X.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=bc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=X.getParameter(a))||W(1280);b=bc(b);break;case 7938:b=bc("OpenGL ES 2.0 ("+X.getParameter(7938)+")");break;case 35724:b=X.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),
b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=bc(b);break;default:return W(1280),0}return Tb[a]=b},lc:function(a,b,c){c?I[c>>2]=X.getTexParameter(a,b):W(1281)},kc:function(a,b,c){c?H[c>>2]=X.getTexParameter(a,b):W(1281)},hc:function(a,b){b=D(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Sb[a]&&Sb[a].$e[b])&&0<=c&&c<a[0]?a[1]+c:-1},jc:function(a,b,c){cc(a,b,c,2)},ic:function(a,b,c){cc(a,b,c,0)},ec:function(a,b,c){c?H[c>>2]=X.getVertexAttribOffset(a,
b):W(1281)},gc:function(a,b,c){dc(a,b,c,2)},fc:function(a,b,c){dc(a,b,c,5)},dc:function(a,b){X.hint(a,b)},cc:function(a){return(a=Nb[a])?X.isBuffer(a):0},bc:function(a){return X.isEnabled(a)},ac:function(a){return(a=Ob[a])?X.isFramebuffer(a):0},$b:function(a){return(a=S[a])?X.isProgram(a):0},ta:function(a){return(a=V[a])?X.Bd.isQueryEXT(a):0},_b:function(a){return(a=Pb[a])?X.isRenderbuffer(a):0},Zb:function(a){return(a=U[a])?X.isShader(a):0},Yb:function(a){return(a=Qb[a])?X.isTexture(a):0},ha:function(a){return(a=
Rb[a])?X.isVertexArray(a):0},Xb:function(a){X.lineWidth(a)},Wb:function(a){X.linkProgram(S[a]);var b=S[a];a=Sb[a]={$e:{},ye:0,Yd:-1,Zd:-1};for(var c=a.$e,d=X.getProgramParameter(b,35718),f=0;f<d;++f){var g=X.getActiveUniform(b,f),h=g.name;a.ye=Math.max(a.ye,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var p=X.getUniformLocation(b,h);if(p){var r=Wb(T);c[h]=[g.size,r];T[r]=p;for(var q=1;q<g.size;++q)p=X.getUniformLocation(b,h+"["+q+"]"),r=Wb(T),T[r]=p}}},Vb:function(a,b){3317==a&&
(Ub=b);X.pixelStorei(a,b)},Ub:function(a,b){X.polygonOffset(a,b)},qa:function(a,b){X.Bd.queryCounterEXT(V[a],b)},Tb:function(a,b,c,d,f,g,h){(h=ec(g,f,c,d,h))?X.readPixels(a,b,c,d,f,g,h):W(1280)},Rb:function(){},Qb:function(a,b,c,d){X.renderbufferStorage(a,b,c,d)},Pb:function(a,b){X.sampleCoverage(a,!!b)},Ob:function(a,b,c,d){X.scissor(a,b,c,d)},Nb:function(){W(1280)},Mb:function(a,b,c,d){for(var f="",g=0;g<b;++g){var h=d?H[d+4*g>>2]:-1;f+=D(H[c+4*g>>2],0>h?void 0:h)}X.shaderSource(U[a],f)},Lb:function(a,
b,c){X.stencilFunc(a,b,c)},Kb:function(a,b,c,d){X.stencilFuncSeparate(a,b,c,d)},Jb:function(a){X.stencilMask(a)},Ib:function(a,b){X.stencilMaskSeparate(a,b)},Hb:function(a,b,c){X.stencilOp(a,b,c)},Gb:function(a,b,c,d){X.stencilOpSeparate(a,b,c,d)},Fb:function(a,b,c,d,f,g,h,p,r){X.texImage2D(a,b,c,d,f,g,h,p,r?ec(p,h,d,f,r):null)},Eb:function(a,b,c){X.texParameterf(a,b,c)},Db:function(a,b,c){X.texParameterf(a,b,I[c>>2])},Cb:function(a,b,c){X.texParameteri(a,b,c)},Bb:function(a,b,c){X.texParameteri(a,
b,H[c>>2])},Ab:function(a,b,c,d,f,g,h,p,r){var q=null;r&&(q=ec(p,h,f,g,r));X.texSubImage2D(a,b,c,d,f,g,h,p,q)},zb:function(a,b){X.uniform1f(T[a],b)},yb:function(a,b,c){if(288>=b)for(var d=fc[b-1],f=0;f<b;++f)d[f]=I[c+4*f>>2];else d=I.subarray(c>>2,c+4*b>>2);X.uniform1fv(T[a],d)},xb:function(a,b){X.uniform1i(T[a],b)},wb:function(a,b,c){if(288>=b)for(var d=hc[b-1],f=0;f<b;++f)d[f]=H[c+4*f>>2];else d=H.subarray(c>>2,c+4*b>>2);X.uniform1iv(T[a],d)},vb:function(a,b,c){X.uniform2f(T[a],b,c)},ub:function(a,
b,c){if(144>=b)for(var d=fc[2*b-1],f=0;f<2*b;f+=2)d[f]=I[c+4*f>>2],d[f+1]=I[c+(4*f+4)>>2];else d=I.subarray(c>>2,c+8*b>>2);X.uniform2fv(T[a],d)},tb:function(a,b,c){X.uniform2i(T[a],b,c)},sb:function(a,b,c){if(144>=b)for(var d=hc[2*b-1],f=0;f<2*b;f+=2)d[f]=H[c+4*f>>2],d[f+1]=H[c+(4*f+4)>>2];else d=H.subarray(c>>2,c+8*b>>2);X.uniform2iv(T[a],d)},rb:function(a,b,c,d){X.uniform3f(T[a],b,c,d)},qb:function(a,b,c){if(96>=b)for(var d=fc[3*b-1],f=0;f<3*b;f+=3)d[f]=I[c+4*f>>2],d[f+1]=I[c+(4*f+4)>>2],d[f+2]=
I[c+(4*f+8)>>2];else d=I.subarray(c>>2,c+12*b>>2);X.uniform3fv(T[a],d)},pb:function(a,b,c,d){X.uniform3i(T[a],b,c,d)},ob:function(a,b,c){if(96>=b)for(var d=hc[3*b-1],f=0;f<3*b;f+=3)d[f]=H[c+4*f>>2],d[f+1]=H[c+(4*f+4)>>2],d[f+2]=H[c+(4*f+8)>>2];else d=H.subarray(c>>2,c+12*b>>2);X.uniform3iv(T[a],d)},mb:function(a,b,c,d,f){X.uniform4f(T[a],b,c,d,f)},lb:function(a,b,c){if(72>=b){var d=fc[4*b-1],f=I;c>>=2;for(var g=0;g<4*b;g+=4){var h=c+g;d[g]=f[h];d[g+1]=f[h+1];d[g+2]=f[h+2];d[g+3]=f[h+3]}}else d=I.subarray(c>>
2,c+16*b>>2);X.uniform4fv(T[a],d)},kb:function(a,b,c,d,f){X.uniform4i(T[a],b,c,d,f)},jb:function(a,b,c){if(72>=b)for(var d=hc[4*b-1],f=0;f<4*b;f+=4)d[f]=H[c+4*f>>2],d[f+1]=H[c+(4*f+4)>>2],d[f+2]=H[c+(4*f+8)>>2],d[f+3]=H[c+(4*f+12)>>2];else d=H.subarray(c>>2,c+16*b>>2);X.uniform4iv(T[a],d)},ib:function(a,b,c,d){if(72>=b)for(var f=fc[4*b-1],g=0;g<4*b;g+=4)f[g]=I[d+4*g>>2],f[g+1]=I[d+(4*g+4)>>2],f[g+2]=I[d+(4*g+8)>>2],f[g+3]=I[d+(4*g+12)>>2];else f=I.subarray(d>>2,d+16*b>>2);X.uniformMatrix2fv(T[a],
!!c,f)},hb:function(a,b,c,d){if(32>=b)for(var f=fc[9*b-1],g=0;g<9*b;g+=9)f[g]=I[d+4*g>>2],f[g+1]=I[d+(4*g+4)>>2],f[g+2]=I[d+(4*g+8)>>2],f[g+3]=I[d+(4*g+12)>>2],f[g+4]=I[d+(4*g+16)>>2],f[g+5]=I[d+(4*g+20)>>2],f[g+6]=I[d+(4*g+24)>>2],f[g+7]=I[d+(4*g+28)>>2],f[g+8]=I[d+(4*g+32)>>2];else f=I.subarray(d>>2,d+36*b>>2);X.uniformMatrix3fv(T[a],!!c,f)},gb:function(a,b,c,d){if(18>=b){var f=fc[16*b-1],g=I;d>>=2;for(var h=0;h<16*b;h+=16){var p=d+h;f[h]=g[p];f[h+1]=g[p+1];f[h+2]=g[p+2];f[h+3]=g[p+3];f[h+4]=g[p+
4];f[h+5]=g[p+5];f[h+6]=g[p+6];f[h+7]=g[p+7];f[h+8]=g[p+8];f[h+9]=g[p+9];f[h+10]=g[p+10];f[h+11]=g[p+11];f[h+12]=g[p+12];f[h+13]=g[p+13];f[h+14]=g[p+14];f[h+15]=g[p+15]}}else f=I.subarray(d>>2,d+64*b>>2);X.uniformMatrix4fv(T[a],!!c,f)},fb:function(a){X.useProgram(S[a])},eb:function(a){X.validateProgram(S[a])},db:function(a,b){X.vertexAttrib1f(a,b)},cb:function(a,b){X.vertexAttrib1f(a,I[b>>2])},bb:function(a,b,c){X.vertexAttrib2f(a,b,c)},ab:function(a,b){X.vertexAttrib2f(a,I[b>>2],I[b+4>>2])},$a:function(a,
b,c,d){X.vertexAttrib3f(a,b,c,d)},_a:function(a,b){X.vertexAttrib3f(a,I[b>>2],I[b+4>>2],I[b+8>>2])},Za:function(a,b,c,d,f){X.vertexAttrib4f(a,b,c,d,f)},Ya:function(a,b){X.vertexAttrib4f(a,I[b>>2],I[b+4>>2],I[b+8>>2],I[b+12>>2])},da:function(a,b){X.vertexAttribDivisor(a,b)},Xa:function(a,b,c,d,f,g){X.vertexAttribPointer(a,b,c,!!d,f,g)},Wa:function(a,b,c,d){X.viewport(a,b,c,d)},g:function(a,b){Z(a,b||1);throw"longjmp";},xa:function(a,b,c){G.copyWithin(a,b,b+c)},ya:function(a){a>>>=0;var b=G.length;
if(1073741824<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ta.grow(Math.min(1073741824,d)-Ga.byteLength+65535>>>16);La(ta.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},za:function(a,b){var c=0;jc().forEach(function(d,f){var g=b+c;H[a+4*f>>2]=g;Fa(d,g);c+=d.length+1});return 0},Aa:function(a,b){var c=jc();H[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});H[b>>2]=d;return 0},
j:function(a){da(a)},l:function(a){try{var b=R(a);O.close(b);return 0}catch(c){return"undefined"!==typeof O&&c instanceof O.nd||w(c),c.rd}},p:function(a,b){try{var c=R(a);A[b>>0]=c.tty?2:O.vd(c.mode)?3:O.Ld(c.mode)?7:4;return 0}catch(d){return"undefined"!==typeof O&&d instanceof O.nd||w(d),d.rd}},Ea:function(a,b,c,d){try{a:{for(var f=R(a),g=a=0;g<c;g++){var h=H[b+(8*g+4)>>2],p=O.read(f,A,H[b+8*g>>2],h,void 0);if(0>p){var r=-1;break a}a+=p;if(p<h)break}r=a}H[d>>2]=r;return 0}catch(q){return"undefined"!==
typeof O&&q instanceof O.nd||w(q),q.rd}},Ta:function(a,b,c,d,f){try{var g=R(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;O.zd(g,a,d);N=[g.position>>>0,(L=g.position,1<=+Math.abs(L)?0<L?(Math.min(+Math.floor(L/4294967296),4294967295)|0)>>>0:~~+Math.ceil((L-+(~~L>>>0))/4294967296)>>>0:0)];H[f>>2]=N[0];H[f+4>>2]=N[1];g.Kd&&0===a&&0===d&&(g.Kd=null);return 0}catch(h){return"undefined"!==typeof O&&h instanceof O.nd||w(h),h.rd}},m:function(a,b,c,d){try{a:{for(var f=R(a),
g=a=0;g<c;g++){var h=O.write(f,A,H[b+8*g>>2],H[b+(8*g+4)>>2],void 0);if(0>h){var p=-1;break a}a+=h}p=a}H[d>>2]=p;return 0}catch(r){return"undefined"!==typeof O&&r instanceof O.nd||w(r),r.rd}},d:function(){return ra|0},f:function(a){var b=Date.now();H[a>>2]=b/1E3|0;H[a+4>>2]=b%1E3*1E3|0;return 0},o:hb,h:vc,nb:wc,Ua:xc,Sb:yc,t:zc,k:Ac,Va:Bc,$:nb,a:ta,Q:function(a){ib();var b=new Date(H[a+20>>2]+1900,H[a+16>>2],H[a+12>>2],H[a+8>>2],H[a+4>>2],H[a>>2],0),c=H[a+32>>2],d=b.getTimezoneOffset(),f=new Date(b.getFullYear(),
0,1),g=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=f.getTimezoneOffset(),p=Math.min(h,g);0>c?H[a+32>>2]=Number(g!=h&&p==d):0<c!=(p==d)&&(g=Math.max(h,g),b.setTime(b.getTime()+6E4*((0<c?p:g)-d)));H[a+24>>2]=b.getDay();H[a+28>>2]=(b.getTime()-f.getTime())/864E5|0;return b.getTime()/1E3|0},Fa:function(a,b){if(0===a)return ub(28),-1;var c=H[a>>2];a=H[a+4>>2];if(0>a||999999999<a||0>c)return ub(28),-1;0!==b&&(H[b>>2]=0,H[b+4>>2]=0);b=1E6*c+a/1E3;for(c=Lb();Lb()-c<b/1E3;);},e:function(a){ra=a|
0},i:function(){return 0},u:function(a,b,c,d){function f(n,u,z){for(n="number"===typeof n?n.toString():n||"";n.length<u;)n=z[0]+n;return n}function g(n,u){return f(n,u,"0")}function h(n,u){function z(P){return 0>P?-1:0<P?1:0}var K;0===(K=z(n.getFullYear()-u.getFullYear()))&&0===(K=z(n.getMonth()-u.getMonth()))&&(K=z(n.getDate()-u.getDate()));return K}function p(n){switch(n.getDay()){case 0:return new Date(n.getFullYear()-1,11,29);case 1:return n;case 2:return new Date(n.getFullYear(),0,3);case 3:return new Date(n.getFullYear(),
0,2);case 4:return new Date(n.getFullYear(),0,1);case 5:return new Date(n.getFullYear()-1,11,31);case 6:return new Date(n.getFullYear()-1,11,30)}}function r(n){n=pc(new Date(n.yd+1900,0,1),n.ke);var u=new Date(n.getFullYear()+1,0,4),z=p(new Date(n.getFullYear(),0,4));u=p(u);return 0>=h(z,n)?0>=h(u,n)?n.getFullYear()+1:n.getFullYear():n.getFullYear()-1}var q=H[d+40>>2];d={Of:H[d>>2],Nf:H[d+4>>2],ie:H[d+8>>2],de:H[d+12>>2],Sd:H[d+16>>2],yd:H[d+20>>2],je:H[d+24>>2],ke:H[d+28>>2],hg:H[d+32>>2],Mf:H[d+
36>>2],Pf:q?D(q):""};c=D(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in q)c=c.replace(new RegExp(t,"g"),q[t]);var x="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
E="January February March April May June July August September October November December".split(" ");q={"%a":function(n){return x[n.je].substring(0,3)},"%A":function(n){return x[n.je]},"%b":function(n){return E[n.Sd].substring(0,3)},"%B":function(n){return E[n.Sd]},"%C":function(n){return g((n.yd+1900)/100|0,2)},"%d":function(n){return g(n.de,2)},"%e":function(n){return f(n.de,2," ")},"%g":function(n){return r(n).toString().substring(2)},"%G":function(n){return r(n)},"%H":function(n){return g(n.ie,
2)},"%I":function(n){n=n.ie;0==n?n=12:12<n&&(n-=12);return g(n,2)},"%j":function(n){return g(n.de+mc(lc(n.yd+1900)?nc:oc,n.Sd-1),3)},"%m":function(n){return g(n.Sd+1,2)},"%M":function(n){return g(n.Nf,2)},"%n":function(){return"\n"},"%p":function(n){return 0<=n.ie&&12>n.ie?"AM":"PM"},"%S":function(n){return g(n.Of,2)},"%t":function(){return"\t"},"%u":function(n){return n.je||7},"%U":function(n){var u=new Date(n.yd+1900,0,1),z=0===u.getDay()?u:pc(u,7-u.getDay());n=new Date(n.yd+1900,n.Sd,n.de);return 0>
h(z,n)?g(Math.ceil((31-z.getDate()+(mc(lc(n.getFullYear())?nc:oc,n.getMonth()-1)-31)+n.getDate())/7),2):0===h(z,u)?"01":"00"},"%V":function(n){var u=new Date(n.yd+1901,0,4),z=p(new Date(n.yd+1900,0,4));u=p(u);var K=pc(new Date(n.yd+1900,0,1),n.ke);return 0>h(K,z)?"53":0>=h(u,K)?"01":g(Math.ceil((z.getFullYear()<n.yd+1900?n.ke+32-z.getDate():n.ke+1-z.getDate())/7),2)},"%w":function(n){return n.je},"%W":function(n){var u=new Date(n.yd,0,1),z=1===u.getDay()?u:pc(u,0===u.getDay()?1:7-u.getDay()+1);n=
new Date(n.yd+1900,n.Sd,n.de);return 0>h(z,n)?g(Math.ceil((31-z.getDate()+(mc(lc(n.getFullYear())?nc:oc,n.getMonth()-1)-31)+n.getDate())/7),2):0===h(z,u)?"01":"00"},"%y":function(n){return(n.yd+1900).toString().substring(2)},"%Y":function(n){return n.yd+1900},"%z":function(n){n=n.Mf;var u=0<=n;n=Math.abs(n)/60;return(u?"+":"-")+String("0000"+(n/60*100+n%60)).slice(-4)},"%Z":function(n){return n.Pf},"%%":function(){return"%"}};for(t in q)0<=c.indexOf(t)&&(c=c.replace(new RegExp(t,"g"),q[t](d)));t=
Db(c,!1);if(t.length>b)return 0;A.set(t,a);return t.length-1},F:function(a){switch(a){case 30:return 16384;case 85:return 65536;case 132:case 133:case 12:case 137:case 138:case 15:case 235:case 16:case 17:case 18:case 19:case 20:case 149:case 13:case 10:case 236:case 153:case 9:case 21:case 22:case 159:case 154:case 14:case 77:case 78:case 139:case 80:case 81:case 82:case 68:case 67:case 164:case 11:case 29:case 47:case 48:case 95:case 52:case 51:case 46:case 79:return 200809;case 27:case 246:case 127:case 128:case 23:case 24:case 160:case 161:case 181:case 182:case 242:case 183:case 184:case 243:case 244:case 245:case 165:case 178:case 179:case 49:case 50:case 168:case 169:case 175:case 170:case 171:case 172:case 97:case 76:case 32:case 173:case 35:return-1;
case 176:case 177:case 7:case 155:case 8:case 157:case 125:case 126:case 92:case 93:case 129:case 130:case 131:case 94:case 91:return 1;case 74:case 60:case 69:case 70:case 4:return 1024;case 31:case 42:case 72:return 32;case 87:case 26:case 33:return 2147483647;case 34:case 1:return 47839;case 38:case 36:return 99;case 43:case 37:return 2048;case 0:return 2097152;case 3:return 65536;case 28:return 32768;case 44:return 32767;case 75:return 16384;case 39:return 1E3;case 89:return 700;case 71:return 256;
case 40:return 255;case 2:return 100;case 180:return 64;case 25:return 20;case 5:return 16;case 6:return 6;case 73:return 4;case 84:return"object"===typeof navigator?navigator.hardwareConcurrency||1:1}ub(28);return-1},s:function(a){var b=Date.now()/1E3|0;a&&(H[a>>2]=b);return b}};
(function(){function a(f){e.asm=f.exports;J=e.asm.Zc;Xa()}function b(f){a(f.instance)}function c(f){return eb().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){k("failed to asynchronously prepare wasm: "+g);w(g)})}var d={a:Cc};Wa();if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return k("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return sa||"function"!==typeof WebAssembly.instantiateStreaming||$a()||Ya("file://")||"function"!==
typeof fetch?c(b):fetch(Za,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){k("wasm streaming compile failed: "+g);k("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
var tc=e.___wasm_call_ctors=function(){return(tc=e.___wasm_call_ctors=e.asm._c).apply(null,arguments)},uc=e._memset=function(){return(uc=e._memset=e.asm.$c).apply(null,arguments)},Da=e._malloc=function(){return(Da=e._malloc=e.asm.ad).apply(null,arguments)},vb=e.___errno_location=function(){return(vb=e.___errno_location=e.asm.bd).apply(null,arguments)};e._fflush=function(){return(e._fflush=e.asm.cd).apply(null,arguments)};e._main=function(){return(e._main=e.asm.dd).apply(null,arguments)};
var mb=e.__get_tzname=function(){return(mb=e.__get_tzname=e.asm.ed).apply(null,arguments)},lb=e.__get_daylight=function(){return(lb=e.__get_daylight=e.asm.fd).apply(null,arguments)},kb=e.__get_timezone=function(){return(kb=e.__get_timezone=e.asm.gd).apply(null,arguments)},B=e.stackSave=function(){return(B=e.stackSave=e.asm.hd).apply(null,arguments)},F=e.stackRestore=function(){return(F=e.stackRestore=e.asm.id).apply(null,arguments)},xa=e.stackAlloc=function(){return(xa=e.stackAlloc=e.asm.jd).apply(null,
arguments)},Z=e._setThrew=function(){return(Z=e._setThrew=e.asm.kd).apply(null,arguments)},Dc=e.dynCall_vijjjid=function(){return(Dc=e.dynCall_vijjjid=e.asm.ld).apply(null,arguments)},Ec=e.dynCall_iiiijj=function(){return(Ec=e.dynCall_iiiijj=e.asm.md).apply(null,arguments)};function vc(a,b,c){var d=B();try{return J.get(a)(b,c)}catch(f){F(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function yc(a,b){var c=B();try{J.get(a)(b)}catch(d){F(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}
function Ac(a,b,c,d,f){var g=B();try{J.get(a)(b,c,d,f)}catch(h){F(g);if(h!==h+0&&"longjmp"!==h)throw h;Z(1,0)}}function zc(a,b,c){var d=B();try{J.get(a)(b,c)}catch(f){F(d);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function wc(a,b,c,d,f,g,h,p,r){var q=B();try{return J.get(a)(b,c,d,f,g,h,p,r)}catch(t){F(q);if(t!==t+0&&"longjmp"!==t)throw t;Z(1,0)}}function Bc(a,b,c,d,f,g,h,p,r,q){var t=B();try{Dc(a,b,c,d,f,g,h,p,r,q)}catch(x){F(t);if(x!==x+0&&"longjmp"!==x)throw x;Z(1,0)}}
function xc(a,b,c,d,f,g,h,p){var r=B();try{return Ec(a,b,c,d,f,g,h,p)}catch(q){F(r);if(q!==q+0&&"longjmp"!==q)throw q;Z(1,0)}}e.ccall=wa;e.cwrap=function(a,b,c,d){c=c||[];var f=c.every(function(g){return"number"===g});return"string"!==b&&f&&!d?va(a):function(){return wa(a,b,c,arguments,d)}};
e.setValue=function(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":A[a>>0]=b;break;case "i8":A[a>>0]=b;break;case "i16":Ha[a>>1]=b;break;case "i32":H[a>>2]=b;break;case "i64":N=[b>>>0,(L=b,1<=+Math.abs(L)?0<L?(Math.min(+Math.floor(L/4294967296),4294967295)|0)>>>0:~~+Math.ceil((L-+(~~L>>>0))/4294967296)>>>0:0)];H[a>>2]=N[0];H[a+4>>2]=N[1];break;case "float":I[a>>2]=b;break;case "double":Ka[a>>3]=b;break;default:w("invalid type for setValue: "+c)}};e.UTF8ToString=D;
e.stringToUTF8=y;e.lengthBytesUTF8=Ba;e.writeAsciiToMemory=Fa;e.FS=O;var Fc;function ca(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Va=function Gc(){Fc||Hc();Fc||(Va=Gc)};
function Hc(a){function b(){if(!Fc&&(Fc=!0,e.calledRun=!0,!ua)){e.noFSInit||O.Vd.te||O.Vd();fb(Oa);O.Ve=!1;fb(Pa);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Ic){var c=a,d=e._main;c=c||[];var f=c.length+1,g=xa(4*(f+1));H[g>>2]=Ea(ia);for(var h=1;h<f;h++)H[(g>>2)+h]=Ea(c[h-1]);H[(g>>2)+f]=0;try{var p=d(f,g);da(p,!0)}catch(r){r instanceof ca||("unwind"==r?noExitRuntime=!0:((c=r)&&"object"===typeof r&&r.stack&&(c=[r,r.stack]),k("exception thrown: "+c),ja(1,r)))}finally{}}if(e.postRun)for("function"==
typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)c=e.postRun.shift(),Ra.unshift(c);fb(Ra)}}a=a||ha;if(!(0<Ta)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Sa();fb(Na);0<Ta||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);b()},1)):b())}}e.run=Hc;function da(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){fb(Qa);O.quit();if(e.onExit)e.onExit(a);ua=!0}ja(a,new ca(a))}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Ic=!1;e.noInitialRun&&(Ic=!1);Hc();


  return createFFmpegCore.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = createFFmpegCore;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return createFFmpegCore; });
    else if (typeof exports === 'object')
      exports["createFFmpegCore"] = createFFmpegCore;
    