[General]
serversUrl=servers.ini
discordUrl=https://discord.gg/yxkVn4wBad

# Auto-load from gameresBaseUrl (CDN load) without showing the import dialog.
autoLoadGameRes=yes
gameresBaseUrl=/v2/
mapsBaseUrl=/map/
modsBaseUrl=/mod/
musicBaseUrl=/music/
gameResArchiveUrl=https://download.ra2web.com/full-pack.7z

# Wang Er Huo Da site content overlay.
patchNotesUrl=
breakingNewsUrl=
ladderRulesUrl=//www.ra2web.com/ladder-rules.html
modSdkUrl=https://github.com/ra2web/mod-sdk
donateUrl="//ra2web.com/#donate"
oldClientsBaseUrl=/old/
quickMatchEnabled=yes
unrankedQueueEnabled=yes
botsEnabled=yes
defaultLanguage=zh-CN
viewport.width=1024
viewport.height=768

[CorsProxy]
archive.org="https://game.chronodivide.com/cors-proxy/?url="
